version: 2.1
orbs:
  slack: circleci/slack@4.4.2

jobs:
  build:
    docker:
      - image: circleci/node:18.12
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: 
          name: Run tests
          command:  cd src && node test-all.js
          
workflows:
  version: 2
  pipeline:
    jobs:
      - build