version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.12-browsers
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: 
          name: Run tests
          command: cd src && node test-all.js

workflows:
  version: 2
  pipeline:
    jobs:
      - build