version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.12-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run: 
          name: Build
          command: npm run build
      - run: 
          name: Run tests
          command: cd src && node test-all.js
      - run:
          name: Git config
          command: |
            git config --global user.email "build@circleci.com" && \
            git config --global user.name "CircleCI"
      - run:
          name: Increment version number
          command: git status && npm version patch && git add package.json && git clean -f
      - run:
          name: Push to GitHub
          command: |
            git commit -m "[skip ci]Increment version" && \
            git push origin master

workflows:
  version: 2
  pipeline:
    jobs:
      - build