version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.12-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ab:bf:60:45:58:a5:e8:8f:16:80:6e:6c:0f:d7:8e:ed"
      - run:
          name: Install dependencies
          command: npm ci
      - run: 
          name: Build
          command: npm run build
      - run: 
          name: Run tests
          command: cd src && node test-all.js
      - run:
          name: Git config
          command: |
            git config --global user.email "build@circleci.com" && \
            git config --global user.name "CircleCI"

      - run: 
          name: GitHub npm auth
          command: npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
      - run:
          name: Push package
          command: git reset --hard && npm version patch && npm publish
      - run:
          name: Push to GitHub
          command: |
            git push origin master

workflows:
  version: 2
  pipeline:
    jobs:
      - build