version: 2.1
##
# The `GHA_Event` parameter will be populated with the value `release` when triggered by
# the GitHub workflow. This can be used in conditional statements to run a specific workflow
# for a specific event.
##
parameters:
  GHA_Event:
    type: string
    default: "push"
  GHA_Actor:
    type: string
    default: "yoshikazu"
  GHA_Action:
    type: string
    default: "bp001"
  GHA_Meta:
    type: string
    default: ""

defaults: &defaults

jobs:
  publish:
    working_directory: ~/repo
    docker:
      - image: cimg/node:19.8.1-browsers

    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .
      - attach_workspace:
          at: ~/repo
      - run: pwd; ls
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN\nregistry=https://registry.npmjs.org\n" > ~/repo/.npmrc
      - run: cat ~/repo/.npmrc
      - run: npm publish --access public

workflows:
  push:
    when:
      equal: [ "push", << pipeline.parameters.GHA_Event >> ]
    jobs:
      - publish:
          # This is mandatory to trigger a pipeline when pushing a tag
          filters:
            tags:
                only: /.*/