version: 2.1
##
# The `GHA_Event` parameter will be populated with the value `release` when triggered by
# the GitHub workflow. This can be used in conditional statements to run a specific workflow
# for a specific event.
##
parameters:
  GHA_Event:
    type: string
    default: "push"
  GHA_Actor:
    type: string
    default: "yoshikazu"
  GHA_Action:
    type: string
    default: "bp001"
  GHA_Meta:
    type: string
    default: ""

jobs:
  publish:
    docker:
      - image: cimg/node:19.8.1-browsers
    steps:
      - checkout
      - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN_CLASSIC
      - run: sudo npm install -g npm@latest --unsafe-perm=true --allow-root
      - run: npm version
      - run: npm publish --access public

workflows:
  push:
    when:
      equal: [ "push", << pipeline.parameters.GHA_Event >> ]
    jobs:
      - publish:
          # This is mandatory to trigger a pipeline when pushing a tag
          filters:
            tags:
                only: /.*/