version: 2.1
orbs:
  slack: circleci/slack@4.4.2
  circleci: leoilab/circleci@1.2.0

jobs:
  build:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - circleci/use-openjdk11
      - run: npm ci --force
      - run: npm run build
      - run: 
          name: Run tests
          command: cd src && node test-all.js

workflows:
  version: 2
  pipeline:
    jobs:
      - build