version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.12-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "73:ac:6b:a7:bb:43:c9:0e:68:05:57:2c:a9:d9:27:a2"
      - run:
          name: Install dependencies
          command: npm ci
      - run: 
          name: Build
          command: npm run build
      - run: 
          name: Run tests
          command: cd src && node test-all.js
      - run:
          name: Git config
          command: |
            git config --global user.email "build@circleci.com" && \
            git config --global user.name "CircleCI"
      - run: 
          name: GitHub npm auth
          command: npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
      - run:
          name: Update version
          command: git reset --hard && npm version patch
      - run:
          name: Publish npm package
          command: npm publish
      - run:
          name: Push to GitHub
          command: |
            git push origin master
      - run:
          name: Trigger Bitmark API build & deploy
          command: |
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Circle-Token: $CIRCLE_TOKEN" \
              -d '{
                  "parameters": {
                    "parser-install": "npm i @bitmark-standard/bitmark-grammar"
                  }
                }' https://circleci.com/api/v2/project/github/getMoreBrain/bitbook-api/pipeline

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          filters:
            branches:
              only: master