on:
  push

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: bitmark-grammar-push-action
        id:   bp001
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
