on:
  push

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpb06/bump-package@latest
        with:
          should-default-to-patch: true	
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v7
        with:
          branch: master
          message: 'Bump package version'
