name: npm-publish
on: push

jobs:
  publish-npm:
    name: Publish bitmark grammar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: jgierer12/npm-auth-gpr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - run: npm whoami
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
